export const SERVICES = [
  { slug: 'flights', title: 'Flight Booking', summary: 'Request domestic or international flight options and booking assistance.', caveat: 'Fares and seats are confirmed with the airline or provider. This form sends a staff assistance request.', fields: [['route', 'Route / cities', 'text'], ['travelDate', 'Travel date', 'date'], ['passengers', 'Travellers', 'number'], ['cabin', 'Cabin preference', 'text']] },
  { slug: 'hotels', title: 'Hotel Booking', summary: 'Request accommodation suited to your destination, dates, rooms and meals.', caveat: 'Property, room type, availability and rate need staff or provider confirmation.', fields: [['destination', 'Destination', 'text'], ['checkIn', 'Check-in', 'date'], ['checkOut', 'Check-out', 'date'], ['rooms', 'Rooms', 'number'], ['mealPlan', 'Meal preference', 'text']] },
  { slug: 'visa', title: 'Visa Services', summary: 'Get a destination-specific document checklist and application coordination.', caveat: 'Visa decisions remain with the relevant embassy or authority.', fields: [['destination', 'Destination country', 'text'], ['nationality', 'Nationality', 'text'], ['purpose', 'Travel purpose', 'text'], ['travelDate', 'Expected travel date', 'date']] },
  { slug: 'attestation', title: 'Attestation', summary: 'Request guidance and coordination for document attestation.', caveat: 'Authority requirements and timelines vary by document, issuing country and intended use.', fields: [['documentType', 'Document type', 'text'], ['issuingCountry', 'Issuing country', 'text'], ['intendedUse', 'Intended use', 'text']] },
  { slug: 'passport', title: 'Passport Assistance', summary: 'Get help with application steps, document checklists and appointment preparation.', caveat: 'Issuance decisions and appointments remain with passport authorities. Do not upload identity documents here.', fields: [['requestType', 'New or renewal', 'text'], ['city', 'Application city', 'text'], ['travelDate', 'Expected travel date', 'date']] },
  { slug: 'insurance', title: 'Travel Insurance', summary: 'Ask about travel insurance information and quotes through an authorized provider.', caveat: 'Coverage, eligibility and claims follow the insurer’s terms; no coverage is confirmed by this request.', fields: [['destination', 'Destination', 'text'], ['travelDate', 'Departure date', 'date'], ['returnDate', 'Return date', 'date'], ['travellers', 'Travellers', 'number']] },
  { slug: 'cars', title: 'Car Rental', summary: 'Request a car and driver or self-drive option for your route.', caveat: 'Vehicle, operator, permits and final price require confirmation.', fields: [['route', 'Pickup, route and drop-off', 'text'], ['travelDate', 'Start date', 'date'], ['travellers', 'Passengers', 'number'], ['luggage', 'Luggage needs', 'text'], ['driver', 'Driver or self-drive', 'text']] },
  { slug: 'buses', title: 'Bus Rental', summary: 'Request group transport by capacity, route and trip type.', caveat: 'Operator, permits and availability require confirmation.', fields: [['route', 'Pickup, route and drop-off', 'text'], ['travelDate', 'Start date', 'date'], ['capacity', 'Passengers / capacity', 'number'], ['tripType', 'Trip type', 'text']] },
  { slug: 'vans', title: 'Van Rental', summary: 'Request a van for your route, dates, passengers and luggage.', caveat: 'Vehicle class, operator and final rate require confirmation.', fields: [['route', 'Pickup, route and drop-off', 'text'], ['travelDate', 'Start date', 'date'], ['travellers', 'Passengers', 'number'], ['luggage', 'Luggage needs', 'text']] }
];
